name: Publish to PyPI

on:
  release:
    types: [created]  # Trigger when a new release is created

jobs:
  deploy:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      # Required for PyPI publishing
      id-token: write  # For trusted publishing
      contents: read   # For checkout
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine
      
      - name: Build distributions
        run: |
          python -m build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # Trusted publishing - no username/password needed
        # Requires PyPI API token configured via GitHub repository settings